#+title: modules
#+PROPERTY: header-args :tangle pspmacs-os.el :mkdirp t :results no :eval no
#+auto_tangle: t

* Modules
- Packages belonging to same category are placed in a module in a tangled org-mode file in modules directory.
  - Categories are prefixed with =pspmacs-= and named in =lower-case-kebab-case=.
#+begin_example
pspmacs-module-category.org
#+end_example
- Wherever available, modular arrangement of packages is according to their level-1 headings in [[https://github.com/emacs-tw/awesome-emacs][emacs-tw/awesome-emacs]].
  - As an exception:
    1. Programming languages (python, R, ...) are maintained as separate modules.
    2. Markup languages (yaml, html, ...) are maintained in =pspmacs-markup.org=.
- Modules are loaded using the function [[file:../late/index.org::*Org mode auto-load][pspmacs/load-inherit]].

* Order of loading modules
- Order of loaded modules follows [[file:load-order.org][modules/load-order.yml]].
- Objects with arbitrary keys containing list of =<module-category>=
  - lists from objects are loaded according to sort-order of object-keys.
- Lists defined in superseding files *replace*
  - To load additional modules, add them with a *new* object key in superseding files.
- Only the earliest occurrence of module =modules/pspmacs-<module-category>.org= in the inheritance work-trees is loaded.
  - Which obviously inherits from others.
  - If not found, error is *NOT* thrown.
