;; -*- coding: utf-8; mode: lisp-data; -*-
'((10 . (keys-cheat-sheet interface-enhancement theme))
  (20 . (editing-enhancement data-vis note))
  (30 . (project-management integration version-control))
  (40 . (programming
         shell
         python
         emacs-lisp
         ess-R
         rust
         javascript
         lua
         conf-format
         markup
         latex))
  (50 . (internet))
  (60 . (multimedia)))
