image: iquiw/alpine-emacs

stages:
- build
- publish

build:
  stage: build
  script:
  - aid/install-pspmacs.sh
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: publish
  script:
  - rm -rf public
  - echo "Exporting to html..."
  - mkdir -p "docs/"
  - emacs --batch --no-init-file --load publish.el --funcall "pspmacs/publish-all"
  - mv docs public
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
